name: CI Develop
on:
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
        id: build_vercel
      - name: Run E2E tests (Cypress)
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ steps.build_vercel.outputs.preview-url }}